<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_alter().
 */
function login_with_salesforce_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['login_with_salesforce'] = [
    '#type' => 'link',
    '#title' => t('Login with Salesforce'),
    '#url' => login_with_salesforce_generate_login_link(),
    '#weight' => 100,
  ];
}

/**
 * Generates "Login with Salesforce" link.
 *
 * @return \Drupal\Core\Url
 */
function login_with_salesforce_generate_login_link() {
  $config = \Drupal::configFactory()->get('login_with_salesforce.settings');
  $login_url = $config->get('login_url');

  $url = Url::fromUri($login_url . '/services/oauth2/authorize', [
    'query' => [
      'response_type' => 'code',
      'client_id' => $config->get('client_id'),
      'redirect_uri' => $config->get('redirect_uri'),
    ]
  ]);

  return $url;
}
